export const size = {
  huge: 50,
  xxxtitle: 38,
  xxtitle: 36,
  xtitle: 34,
  title: 32,
  h1: 30,
  h2: 28,
  h3: 26,
  h4: 25,
  h5: 24,
  h6: 22,
  xxlarge: 20,
  xlarge: 19,
  large: 18,
  medium: 17,
  normal: 16,
  small: 15,
  xsmall: 14,
  xxsmall: 13,
  tiny: 12,
  xtiny: 11,
  xxtiny: 10,
  xxxtiny: 9,
};

export const family = {
  Jost_ThinItalic: 'Jost-ThinItalic',
  Jost_Thin: 'Jost-Thin',
  Jost_SemiBoldItalic: 'Jost-SemiBoldItalic',
  Jost_SemiBold: 'Jost-SemiBold',
  Jost_Regular: 'Jost-Regular',
  Jost_MediumItalic: 'Jost-MediumItalic',
  Jost_Medium: 'Jost-Medium',
  Jost_LightItalic: 'Jost-LightItalic',
  Jost_Light: 'Jost-Light',
  Jost_Italic: 'Jost-Italic',
  Jost_ExtraLightItalic: 'Jost-ExtraLightItalic',
  Jost_ExtraLight: 'Jost-ExtraLight',
  Jost_ExtraBoldItalic: 'Jost-ExtraBoldItalic',
  Jost_ExtraBold: 'Jost-ExtraBold',
  Jost_BoldItalic: 'Jost-BoldItalic',
  Jost_Bold: 'Jost-Bold',
  Jost_BlackItalic: 'Jost-BlackItalic',
  Jost_Black: 'Jost-Black',
  Giddyup_Std: 'Giddyup-Std',
};
